name: ci

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Set up QEMU (for multi-platform builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push using Git context
      - name: Build and push using Git context
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:mysubdir"  # Specify a subdirectory within Git context
          push: true
          tags: user/app:latest

      # Alternative build using Path context
      - name: Build and push using Path context
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest

      # Build and push with private Git repository authentication
      - name: Build and push with private Git repo authentication
        uses: docker/build-push-action@v6  # Reference action from https://github.com/docker/build-push-action
        with:
          push: true
          tags: user/app:private-latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
