name: Simple CI Pipeline


on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t heinzt/myapp:latest .

      - name: Push Docker image to Docker Hub
        run: docker push heinzt/myapp:latest
